# Generated by Django 3.0.2 on 2020-09-25 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeRazao', models.CharField(max_length=50, verbose_name='Nome/Razão social')),
                ('CpfCnpj', models.CharField(blank=True, max_length=50, verbose_name='CPF/CNPJ')),
                ('InscEstadual', models.CharField(blank=True, max_length=50, verbose_name='Inscrição estadual')),
                ('Telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('Celular', models.CharField(blank=True, max_length=50, verbose_name='Celular')),
                ('Contato', models.CharField(blank=True, max_length=50, verbose_name='Contato')),
                ('Email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('Status', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('EXCLUIDO', 'EXCLUIDO')], default='ATIVO', max_length=10, verbose_name='Státus')),
                ('Cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('Endereco', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('Bairro', models.CharField(blank=True, max_length=50, verbose_name='Bairro')),
                ('Cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('Estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('Observacoes', models.TextField(blank=True, max_length=200, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('NomeRazao',),
            },
        ),
    ]
